# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeForDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='secondary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recipeforday',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recept.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeforday',
            unique_together=set([('recipe', 'date')]),
        ),
    ]
