# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recept', '0002_auto_20170503_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeForWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('recipes', models.ManyToManyField(to='Recept.Recipe')),
            ],
            options={
                'ordering': ['year', 'week'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='recipeforday',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='recipeforday',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='RecipeForDay',
        ),
        migrations.AlterUniqueTogether(
            name='recipeforweek',
            unique_together=set([('year', 'week')]),
        ),
    ]
